services:
  - type: web
    name: royal-store-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEPLOY_PLATFORM
        value: render
      - key: PORT
        value: 10000
    autoDeploy: false
